name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET
      uses: xt0rted/setup-dotnet@v1.0.0
      with:
        dotnet-version: 6.0.201
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o website
    - name: Upload a Build Artifact for deployment job
      uses: actions/upload-artifact@v3.1.0
      with:        
        name: webapp
        path: website/**
        if-no-files-found: warn     
